### PR TITLE
Todos React App

### PR DESCRIPTION
**Pull request by Marcraphael12**
In this PR, we are creating a to-do app with React Following a tutorial. The App should
- Allows users to add a new item to the list
- Allows users to delete an item from the List
- Allows to check and uncheck an item
Have a good review!

### CODE REVIEW

**Comment by admirerbrown** [comment]
### **Hello @Marcraphael12** , 
Good job on building a working project ,however there are some small changes  until you move on to the next project. **see changes below**:

### **🥇 HIGHLIGHTS**

- 💪🏾 Great job on making the app function as expected.
- 🥇 your app looks  good and clean
- ✅ Good professional and descriptive readme
- ✅ Good commit history and messages.

### REQUESTED CHANGES♻️

- [ ] Please ensure to add linters to your project. Linters  keep you in check and helps you write clean, consistent and maintainable code.

**Comment by Marcraphael12** [comment]
Thanks... i'll manage to apply that

**Comment by admirerbrown** [comment]
### STATUS:  ☑️ APPROVED.
Hello @Marcraphael12 , Hurray 🥳 your  project is  💯  complete. At this point there is nothing more excerpt it's time to 👍🏾 merge!!

8tuI

### HIGHLIGHTS:

- [x] Good looking UI
- [x] Good job implementing code review suggestions.

🏁 Good job done.

**Comment by Marcraphael12** [comment]
Thanks for reviewing and approving my project

**Pull request merged**
